### ISSUE TITLE
Typo in README?

### ISSUE THREAD

**Issue by disambiguator** [amandaghassaei/canvas-capture#5]
I see `bindKeyToPNGFrames` in the code, but the README shows an example using `bindKeyToPNGFramesRecord`. Is this a typo?

**Comment by amandaghassaei** [comment]
Good catch!  I've updated the api to be `bindKeyToPNGFramesRecord` and `bindKeyToJPEGFramesRecord` since that was more consistent with the other api methods.  

https://github.com/amandaghassaei/canvas-capture/commit/5feba695737940ddc9b68087dce2da9be411c6c3

the latest is pushed to npm (version 1.2)
